#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iteration

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then 
		echo "bad luck"
		(( i++ ))
	elif [ $i -eq 7 ]
	then
		echo "good luck"
		(( i++))
	else
		echo "Best School"
		(( i++ ))
	fi
done
