#!/usr/bin/env bash
# Client configuration file

Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    HashKnownHosts yes
    SendEnv LANG LC_*
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no

